[package]
name = "personal-finance"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
json = "0.12.4"
rusqlite = { version = "0.36.0", features = ["bundled", "chrono"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
uuid = { version = "1.17.0", features = ["v7"] }
